---
- name: helm | uninstall package
  tags:
  - package
  package:
    name: helm
    state: absent

- name: helm | remove files
  file:
    path: "{{ item }}"
    state: absent
  loop:
  - "{{ helm_bash_completion }}"
  - /etc/apt/sources.list.d/helm.list
  - "{{ helm_apt_keyring }}"
