#! /usr/bin/env ansible-playbook
# Configure helm kubernetes release manager
# Replace 'k8s_admin' with your own inventory group
---
- name: helm | kubernetes release manager
  hosts: k8s_admin
  roles:
  - role: helm
    tags:
    - helm
    - k8s
    - kubernetes
